### PR TITLE
Parameterized IOC Shell Scripts to initialize octal modules

### PR DESCRIPTION
**Pull request by keenanlang**
This pull request is part of a series of pull requests to try and move all device/module specific IOC support into their respective epics modules. This will not only make the xxx startup scripts much easier to maintain, understand, and update, but this will make sure that support is more likely to be kept up to date as the people who are designing the device support are the ones keeping track of the shell scripts.

[Further Information](https://github.com/epics-modules/xxx/wiki/IOC-Shell-Scripts)

### CODE REVIEW

**Comment by anjohnson** [comment]
Hi Keenan,

Is there any documentation somewhere about these iocsh scripts that you're adding to all the synapps modules? Will someone be presenting a talk about them at the SNS meeting in September? Have they even been discussed with anyone outside of BCDA?

I'm not necessarily against them, but I would like to see some online documentation somewhere (not here in the ipac module obviously) and an explanation of how they're intended to be used. I would then expect to see an entry in the release notes for these two ipac sub-modules with a link to that documentation and an example showing a call to each script.

I think that's probably going to be a requirement for merging this commit.

**Comment by ulrikpedersen** [comment]
I second @anjohnson's requests: I have been following these iocsh Pull Requests on all modules but I'm unsure what they're for and how they're to be used... It doesn't seem to be invasive and might be really useful so I'm not against the addition. I just hope they are not a site-specific feature(?)

**Comment by keenanlang** [comment]
@anjohnson 
> Is there any documentation somewhere about these iocsh scripts that you're adding to all the synapps modules?

Each script is documented with the required environment variables to use them, any module with an iocBoot directory can have their example startup scripts changed to show the use of them, and the XXX module is going to be changed to call these scripts. The Application Developers Guide also provides documentation on how to use iocshLoad. 

I will additionally update the release notes, and I guess I can write a quick wiki page for the xxx module to talk about iocshLoad'ing of command scripts. I don't exactly know where else to put such documentation since it's a feature of base.


@ulrikpedersen 
>I just hope they are not a site-specific feature(?)

All they are are startup scripts meant to be used with the IOC shell, here is nothing site-specific about them. They are designed to be used with epics base 3.15 due to the addition of iocshLoad and iocshRun, but for most of them they can be used with a lower version of base if the named variables are set with epicsEnvSet.

**Comment by anjohnson** [comment]
It's not docs on the individual scripts that I'm asking for, I agree that the detailed description in the top of each is good and mostly sufficient for that script. My point is that you are setting a standard which the rest of the community may want to adopt, and I'd like someone to explain the standard, preferably with a URL that we can point questioners to when they ask about this. At least publish a relatively simple example showing an IOC which uses just one or two modules (not the whole shebang of xxx, this would be a tool for education not an attempt to show off the whole of synapps).

The synapps xxx module is used at some (maybe most) of the beamlines here, but not by the accelerator IOCs and probably somewhat less elsewhere. The documentation of the [`iocshLoad` command](http://www.aps.anl.gov/epics/base/R3-15/4-docs/AppDevGuide/node19.html#SECTION001930000000000000000) in the AppDevGuide is fine, but it doesn't do the job of showing how this functionality makes complex configuration tasks easier. One or more wiki pages on the xxx module's github area would be a good spot for this.

I wish BCDA were sending someone to SNS to talk about this too. I think it could be very well received, but without publicity it might be regarded as "just another slightly weird thing that the synapps guys do that we don't understand so we're going to carry on doing things the way we always have."

Here are some questions I would like to see answered in such a document:
* Show me an example of an IOC startup script calling these
* What do I have to do to write my own script?
* How should my script handle supporting more than one instance of a device in the same IOC?
* Is there a standard location in the filesystem for these scripts? What happens if I put mine elsewhere?
* What little tips and tricks have you learned that I can use in my scripts?
* Are those `#-` comment lines special somehow?

BTW, please take these comments as encouragement, not as criticism of this solution!

- Andrew

**Comment by ulrikpedersen** [comment]
@keenanlang 

> All they are are startup scripts meant to be used with the IOC shell, there is nothing site-specific about them. They are designed to be used with epics base 3.15 due to the addition of iocshLoad and iocshRun, but for most of them they can be used with a lower version of base if the named variables are set with epicsEnvSet.

Many thanks for the explanation. I was not aware of these 3.15 features. It seems like a good idea.

**Pull request merged**
